title: Robbie Meyer
baseurl: ""
url: "robbiemeyer.com"
permalink: /:categories/:year/:month/:day/:title

collections:
  projects:
    output: true
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
      navbar: projects
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      navbar: blog
