title: Robbie Meyer
baseurl: ""
url: "http://robbiemeyer.com"
permalink: /:categories/:year/:month/:day/:title

plugins:
  - jekyll-redirect-from

collections:
  projects:
    output: true
  posts:
    permalink: /blog/:categories/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
      navbar: projects
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      navbar: blog
