title: Robbie Meyer
baseurl: ""
url: "robbiemeyer.com"
permalink: /:categories/:year/:month/:day/:title

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: default
